In [1]:
import json, glob, re, pycm, pandas as pd, numpy as np, seaborn as sns, matplotlib.pyplot as plt, scipy.stats as stats
from IPython.display import display, Markdown

In [162]:
RUN_VERSION = "v29"

In [ ]:
data = []
for file in glob.glob(f"experiments/{RUN_VERSION}/*.json"):
    match = re.match(r'experiments/.+/(.+)-(baseline|zero|few)-(gpqa|simpleqa|mmlu-pro).json', file)
    model = match.group(1)
    prompt = match.group(2)
    dataset = match.group(3)
    df = pd.DataFrame(json.load(open(file, 'r')))
    keys = {
        "Judge Model": model,
        "Prompt": prompt,
        "Dataset": dataset
    }
    n = len(df)
    wk_v_counts = df["wk_v"].value_counts()
    wk_v_freq = (wk_v_counts / n).to_dict()
    I_freq = {
        '<t,t>': 0.0, 
        '<t,e>': 0.0, 
        '<t,f>': 0.0, 
        '<e,t>': 0.0, 
        '<e,e>': 0.0, 
        '<e,f>': 0.0, 
        '<f,t>': 0.0, 
        '<f,e>': 0.0, 
        '<f,f>': 0.0
    }
    I_counts = df["I"].value_counts()
    I_freq_rec = (I_counts / n).to_dict()
    for tv in I_freq_rec:
        I_freq[tv] = I_freq_rec[tv]
    addl_stats = { 
        'avg execution time': df['execution_time'].mean(),
        'std execution time': df['execution_time'].std(),
        'avg tokens used': df['tokens_used'].mean(),
        'std tokens used': df['tokens_used'].std(),
        'coverage': (n - wk_v_counts['e']) / n
    }
    data.append({ **keys, **wk_v_freq, **I_freq, **addl_stats })
df1 = pd.DataFrame.from_records(data)
df1 = df1.round(3)
df1 = df1.sort_values(["Judge Model", "Dataset", "Prompt"])

In [249]:
df1

,Judge Model,Prompt,Dataset,e,f,t,"<t,t>","<t,e>","<t,f>","<e,t>","<e,e>","<e,f>","<f,t>","<f,e>","<f,f>",avg execution time,std execution time,avg tokens used,std tokens used,coverage
33,claude-3-5-haiku-20241022,baseline,gpqa,0.16,0.25,0.59,0.08,0.0,0.59,0.0,0.0,0.0,0.25,0.0,0.08,31.859,4.485,2642.59,648.881,0.84
14,claude-3-5-haiku-20241022,few,gpqa,0.53,0.19,0.28,0.48,0.0,0.28,0.0,0.0,0.0,0.19,0.0,0.05,46.959,4.305,7656.06,648.157,0.47
19,claude-3-5-haiku-20241022,zero,gpqa,0.58,0.19,0.23,0.50,0.0,0.23,0.0,0.0,0.0,0.19,0.0,0.08,43.194,3.771,4216.20,660.958,0.42
34,claude-3-5-haiku-20241022,baseline,simpleqa,0.52,0.18,0.30,0.01,0.0,0.30,0.0,0.0,0.0,0.18,0.0,0.51,15.979,3.291,1009.33,163.143,0.48
26,claude-3-5-haiku-20241022,few,simpleqa,0.61,0.21,0.18,0.14,0.0,0.18,0.0,0.0,0.0,0.21,0.0,0.47,41.053,4.229,6438.93,179.820,0.39
31,claude-3-5-haiku-20241022,zero,simpleqa,0.69,0.20,0.11,0.18,0.0,0.11,0.0,0.0,0.0,0.20,0.0,0.51,39.042,3.166,3107.98,143.984,0.31
24,claude-3-5-sonnet-20241022,baseline,gpqa,0.23,0.34,0.43,0.19,0.0,0.43,0.0,0.0,0.0,0.34,0.0,0.04,39.542,6.273,2965.82,765.463,0.77
4,claude-3-5-sonnet-20241022,few,gpqa,0.44,0.33,0.23,0.43,0.0,0.23,0.0,0.0,0.0,0.33,0.0,0.01,60.267,5.255,8043.21,702.081,0.56
17,claude-3-5-sonnet-20241022,zero,gpqa,0.49,0.30,0.21,0.45,0.0,0.21,0.0,0.0,0.0,0.30,0.0,0.04,61.849,5.505,4848.79,704.905,0.51
18,claude-3-5-sonnet-20241022,baseline,simpleqa,0.47,0.30,0.23,0.04,0.0,0.23,0.0,0.0,0.0,0.30,0.0,0.43,23.781,5.082,1197.56,187.527,0.53
29,claude-3-5-sonnet-20241022,few,simpleqa,0.39,0.49,0.12,0.32,0.0,0.12,0.0,0.0,0.0,0.49,0.0,0.07,49.797,4.952,6710.15,178.076,0.61
25,claude-3-5-sonnet-20241022,zero,simpleqa,0.41,0.41,0.18,0.28,0.0,0.18,0.0,0.0,0.0,0.41,0.0,0.13,50.421,7.468,3451.77,181.075,0.59
11,llama-4-maverick,baseline,gpqa,0.15,0.43,0.42,0.05,0.0,0.42,0.0,0.0,0.0,0.43,0.0,0.10,87.650,96.517,6203.86,1411.934,0.85
10,llama-4-maverick,few,gpqa,0.17,0.39,0.44,0.13,0.0,0.44,0.0,0.0,0.0,0.39,0.0,0.04,75.691,71.195,9906.28,1393.106,0.83
2,llama-4-maverick,zero,gpqa,0.38,0.38,0.24,0.35,0.0,0.24,0.0,0.0,0.0,0.38,0.0,0.03,77.484,54.368,7425.84,1237.048,0.62
8,llama-4-maverick,baseline,simpleqa,0.19,0.17,0.64,0.08,0.0,0.64,0.0,0.0,0.0,0.17,0.0,0.11,20.341,17.351,2128.23,1090.677,0.81
12,llama-4-maverick,few,simpleqa,0.26,0.16,0.58,0.21,0.0,0.58,0.0,0.0,0.0,0.16,0.0,0.05,62.992,52.715,6720.11,558.011,0.74
6,llama-4-maverick,zero,simpleqa,0.41,0.17,0.42,0.41,0.0,0.42,0.0,0.0,0.0,0.17,0.0,0.00,37.416,9.891,4444.56,445.311,0.59
9,llama-4-scout,baseline,gpqa,0.28,0.37,0.35,0.07,0.0,0.35,0.0,0.0,0.0,0.37,0.0,0.21,64.159,29.914,5425.48,1792.919,0.72
23,llama-4-scout,few,gpqa,0.31,0.31,0.38,0.26,0.0,0.38,0.0,0.0,0.0,0.31,0.0,0.05,79.886,63.150,9562.13,1382.014,0.69
20,llama-4-scout,zero,gpqa,0.51,0.25,0.24,0.46,0.0,0.24,0.0,0.0,0.0,0.25,0.0,0.05,97.701,76.095,7077.75,1313.333,0.49
32,llama-4-scout,baseline,simpleqa,0.40,0.18,0.42,0.15,0.0,0.42,0.0,0.0,0.0,0.18,0.0,0.25,17.784,9.372,1418.57,429.215,0.60
28,llama-4-scout,few,simpleqa,0.32,0.09,0.59,0.25,0.0,0.59,0.0,0.0,0.0,0.09,0.0,0.07,55.762,47.242,6324.04,491.583,0.68
13,llama-4-scout,zero,simpleqa,0.69,0.10,0.21,0.68,0.0,0.21,0.0,0.0,0.0,0.10,0.0,0.01,38.955,10.228,4093.40,415.481,0.31
3,nf-gpt-4o,baseline,gpqa,0.30,0.35,0.35,0.13,0.0,0.35,0.0,0.0,0.0,0.35,0.0,0.17,5.344,9.002,1140.58,548.662,0.70
35,nf-gpt-4o,few,gpqa,0.50,0.35,0.15,0.48,0.0,0.15,0.0,0.0,0.0,0.35,0.0,0.02,30.900,8.627,8593.42,1344.822,0.50
22,nf-gpt-4o,zero,gpqa,0.53,0.34,0.13,0.50,0.0,0.13,0.0,0.0,0.0,0.34,0.0,0.03,33.863,8.533,6043.14,1206.896,0.47
27,nf-gpt-4o,baseline,simpleqa,0.29,0.23,0.48,0.09,0.0,0.48,0.0,0.0,0.0,0.23,0.0,0.20,4.682,9.068,482.58,68.571,0.71
15,nf-gpt-4o,few,simpleqa,0.53,0.30,0.17,0.51,0.0,0.17,0.0,0.0,0.0,0.30,0.0,0.02,16.436,2.249,6100.83,316.415,0.47
5,nf-gpt-4o,zero,simpleqa,0.60,0.31,0.09,0.60,0.0,0.09,0.0,0.0,0.0,0.31,0.0,0.00,20.890,3.066,3765.60,313.735,0.40
1,nf-gpt-4o-mini,baseline,gpqa,0.31,0.52,0.17,0.17,0.0,0.17,0.0,0.0,0.0,0.52,0.0,0.14,15.665,12.253,3006.93,1824.420,0.69
16,nf-gpt-4o-mini,few,gpqa,0.47,0.50,0.03,0.47,0.0,0.03,0.0,0.0,0.0,0.50,0.0,0.00,29.396,7.157,8821.26,1138.869,0.53
21,nf-gpt-4o-mini,zero,gpqa,0.57,0.42,0.01,0.57,0.0,0.01,0.0,0.0,0.0,0.42,0.0,0.00,27.815,5.365,5816.23,909.068,0.43
30,nf-gpt-4o-mini,baseline,simpleqa,0.27,0.49,0.24,0.12,0.0,0.24,0.0,0.0,0.0,0.49,0.0,0.15,2.512,1.083,492.69,80.665,0.73
7,nf-gpt-4o-mini,few,simpleqa,0.50,0.17,0.33,0.43,0.0,0.33,0.0,0.0,0.0,0.17,0.0,0.07,15.596,1.829,6339.67,264.302,0.50
0,nf-gpt-4o-mini,zero,simpleqa,0.61,0.32,0.07,0.61,0.0,0.07,0.0,0.0,0.0,0.32,0.0,0.00,18.832,2.335,3820.86,261.960,0.39

In [ ]:
cms = {}
for file in glob.glob(f"experiments/{RUN_VERSION}/*.json"):
    match = re.match(r'experiments/.+/(.+)-(baseline|zero|few)-(gpqa|simpleqa|mmlu-pro).json', file)
    model = match.group(1)
    prompt = match.group(2)
    dataset = match.group(3)
    if model not in cms:
        cms[model] = {}
    if prompt not in cms[model]:
        cms[model][prompt] = {}
    df = pd.DataFrame.from_records(json.load(open(file, 'r')))
    cms[model][prompt][dataset] = pycm.ConfusionMatrix(df["label"].tolist(), df["wk_v"].tolist(), digit=2, classes=[ 't', 'f' ])

data = [
    [ 
        model, 
        prompt, 
        dataset, 
        cms[model][prompt][dataset].F1_Macro, 
        cms[model][prompt][dataset].ACC_Macro, 
        cms[model][prompt][dataset].FPR['t'], 
        cms[model][prompt][dataset].FNR['t'], 
        cms[model][prompt][dataset].F1['t'], 
        cms[model][prompt][dataset].F1['f']
    ] 
    for model in cms 
    for prompt in cms[model] 
    for dataset in cms[model][prompt]
]

column_names = ["Judge Model", "Prompt", "Dataset", "Macro-F1", "Acc.", "FPR", "FNR", "F1 (+)", "F1 (-)"]
df2 = pd.DataFrame(data, columns=column_names)
df2 = df2.round(3)
df2 = df2.sort_values(["Judge Model", "Dataset", "Prompt"])

In [234]:
df2

,Judge Model,Prompt,Dataset,Macro-F1,Acc.,FPR,FNR,F1 (+),F1 (-)
34,claude-3-5-haiku-20241022,baseline,gpqa,0.562,0.571,0.617,0.189,0.625,0.500
30,claude-3-5-haiku-20241022,few,gpqa,0.638,0.638,0.464,0.211,0.638,0.638
32,claude-3-5-haiku-20241022,zero,gpqa,0.660,0.667,0.414,0.154,0.611,0.708
35,claude-3-5-haiku-20241022,baseline,simpleqa,0.666,0.667,0.464,0.150,0.680,0.652
31,claude-3-5-haiku-20241022,few,simpleqa,0.606,0.615,0.375,0.400,0.545,0.667
33,claude-3-5-haiku-20241022,zero,simpleqa,0.689,0.710,0.211,0.417,0.609,0.769
23,claude-3-5-sonnet-20241022,baseline,gpqa,0.701,0.701,0.366,0.222,0.709,0.693
18,claude-3-5-sonnet-20241022,few,gpqa,0.708,0.714,0.226,0.360,0.667,0.750
20,claude-3-5-sonnet-20241022,zero,gpqa,0.717,0.725,0.233,0.333,0.667,0.767
22,claude-3-5-sonnet-20241022,baseline,simpleqa,0.866,0.868,0.103,0.167,0.851,0.881
19,claude-3-5-sonnet-20241022,few,simpleqa,0.642,0.689,0.059,0.630,0.513,0.771
21,claude-3-5-sonnet-20241022,zero,simpleqa,0.835,0.847,0.029,0.320,0.791,0.880
9,llama-4-maverick,baseline,gpqa,0.786,0.788,0.255,0.147,0.763,0.809
10,llama-4-maverick,few,gpqa,0.771,0.771,0.262,0.195,0.776,0.765
6,llama-4-maverick,zero,gpqa,0.773,0.790,0.195,0.238,0.711,0.835
8,llama-4-maverick,baseline,simpleqa,0.611,0.654,0.649,0.091,0.741,0.481
11,llama-4-maverick,few,simpleqa,0.607,0.649,0.647,0.100,0.735,0.480
7,llama-4-maverick,zero,simpleqa,0.644,0.661,0.552,0.133,0.722,0.565
24,llama-4-scout,baseline,gpqa,0.763,0.764,0.250,0.219,0.746,0.779
28,llama-4-scout,few,gpqa,0.710,0.710,0.351,0.219,0.714,0.706
27,llama-4-scout,zero,gpqa,0.795,0.796,0.222,0.182,0.783,0.808
25,llama-4-scout,baseline,simpleqa,0.583,0.600,0.600,0.200,0.667,0.500
29,llama-4-scout,few,simpleqa,0.494,0.574,0.812,0.083,0.695,0.293
26,llama-4-scout,zero,simpleqa,0.748,0.774,0.364,0.150,0.829,0.667
12,nf-gpt-4o,baseline,gpqa,0.556,0.557,0.447,0.438,0.537,0.575
17,nf-gpt-4o,few,gpqa,0.670,0.700,0.167,0.500,0.571,0.769
15,nf-gpt-4o,zero,gpqa,0.621,0.660,0.179,0.579,0.500,0.742
13,nf-gpt-4o,baseline,simpleqa,0.638,0.648,0.528,0.171,0.699,0.576
16,nf-gpt-4o,few,simpleqa,0.782,0.787,0.083,0.348,0.750,0.815
14,nf-gpt-4o,zero,simpleqa,0.772,0.800,0.000,0.471,0.692,0.852
2,nf-gpt-4o-mini,baseline,gpqa,0.456,0.522,0.268,0.786,0.267,0.645
5,nf-gpt-4o-mini,few,gpqa,0.361,0.566,0.091,1.000,0.000,0.723
1,nf-gpt-4o-mini,zero,gpqa,0.368,0.581,0.038,1.000,0.000,0.735
3,nf-gpt-4o-mini,baseline,simpleqa,0.547,0.562,0.270,0.611,0.467,0.628
4,nf-gpt-4o-mini,few,simpleqa,0.517,0.520,0.621,0.286,0.556,0.478
0,nf-gpt-4o-mini,zero,simpleqa,0.458,0.538,0.182,0.824,0.250,0.667

In [250]:
df = df2.merge(df1, on=['Judge Model', 'Prompt', 'Dataset'], how='inner')

In [251]:
df

,Judge Model,Prompt,Dataset,Macro-F1,Acc.,FPR,FNR,F1 (+),F1 (-),e,...,"<e,e>","<e,f>","<f,t>","<f,e>","<f,f>",avg execution time,std execution time,avg tokens used,std tokens used,coverage
0,claude-3-5-haiku-20241022,baseline,gpqa,0.562,0.571,0.617,0.189,0.625,0.500,0.16,...,0.0,0.0,0.25,0.0,0.08,31.859,4.485,2642.59,648.881,0.84
1,claude-3-5-haiku-20241022,few,gpqa,0.638,0.638,0.464,0.211,0.638,0.638,0.53,...,0.0,0.0,0.19,0.0,0.05,46.959,4.305,7656.06,648.157,0.47
2,claude-3-5-haiku-20241022,zero,gpqa,0.660,0.667,0.414,0.154,0.611,0.708,0.58,...,0.0,0.0,0.19,0.0,0.08,43.194,3.771,4216.20,660.958,0.42
3,claude-3-5-haiku-20241022,baseline,simpleqa,0.666,0.667,0.464,0.150,0.680,0.652,0.52,...,0.0,0.0,0.18,0.0,0.51,15.979,3.291,1009.33,163.143,0.48
4,claude-3-5-haiku-20241022,few,simpleqa,0.606,0.615,0.375,0.400,0.545,0.667,0.61,...,0.0,0.0,0.21,0.0,0.47,41.053,4.229,6438.93,179.820,0.39
5,claude-3-5-haiku-20241022,zero,simpleqa,0.689,0.710,0.211,0.417,0.609,0.769,0.69,...,0.0,0.0,0.20,0.0,0.51,39.042,3.166,3107.98,143.984,0.31
6,claude-3-5-sonnet-20241022,baseline,gpqa,0.701,0.701,0.366,0.222,0.709,0.693,0.23,...,0.0,0.0,0.34,0.0,0.04,39.542,6.273,2965.82,765.463,0.77
7,claude-3-5-sonnet-20241022,few,gpqa,0.708,0.714,0.226,0.360,0.667,0.750,0.44,...,0.0,0.0,0.33,0.0,0.01,60.267,5.255,8043.21,702.081,0.56
8,claude-3-5-sonnet-20241022,zero,gpqa,0.717,0.725,0.233,0.333,0.667,0.767,0.49,...,0.0,0.0,0.30,0.0,0.04,61.849,5.505,4848.79,704.905,0.51
9,claude-3-5-sonnet-20241022,baseline,simpleqa,0.866,0.868,0.103,0.167,0.851,0.881,0.47,...,0.0,0.0,0.30,0.0,0.43,23.781,5.082,1197.56,187.527,0.53
10,claude-3-5-sonnet-20241022,few,simpleqa,0.642,0.689,0.059,0.630,0.513,0.771,0.39,...,0.0,0.0,0.49,0.0,0.07,49.797,4.952,6710.15,178.076,0.61
11,claude-3-5-sonnet-20241022,zero,simpleqa,0.835,0.847,0.029,0.320,0.791,0.880,0.41,...,0.0,0.0,0.41,0.0,0.13,50.421,7.468,3451.77,181.075,0.59
12,llama-4-maverick,baseline,gpqa,0.786,0.788,0.255,0.147,0.763,0.809,0.15,...,0.0,0.0,0.43,0.0,0.10,87.650,96.517,6203.86,1411.934,0.85
13,llama-4-maverick,few,gpqa,0.771,0.771,0.262,0.195,0.776,0.765,0.17,...,0.0,0.0,0.39,0.0,0.04,75.691,71.195,9906.28,1393.106,0.83
14,llama-4-maverick,zero,gpqa,0.773,0.790,0.195,0.238,0.711,0.835,0.38,...,0.0,0.0,0.38,0.0,0.03,77.484,54.368,7425.84,1237.048,0.62
15,llama-4-maverick,baseline,simpleqa,0.611,0.654,0.649,0.091,0.741,0.481,0.19,...,0.0,0.0,0.17,0.0,0.11,20.341,17.351,2128.23,1090.677,0.81
16,llama-4-maverick,few,simpleqa,0.607,0.649,0.647,0.100,0.735,0.480,0.26,...,0.0,0.0,0.16,0.0,0.05,62.992,52.715,6720.11,558.011,0.74
17,llama-4-maverick,zero,simpleqa,0.644,0.661,0.552,0.133,0.722,0.565,0.41,...,0.0,0.0,0.17,0.0,0.00,37.416,9.891,4444.56,445.311,0.59
18,llama-4-scout,baseline,gpqa,0.763,0.764,0.250,0.219,0.746,0.779,0.28,...,0.0,0.0,0.37,0.0,0.21,64.159,29.914,5425.48,1792.919,0.72
19,llama-4-scout,few,gpqa,0.710,0.710,0.351,0.219,0.714,0.706,0.31,...,0.0,0.0,0.31,0.0,0.05,79.886,63.150,9562.13,1382.014,0.69
20,llama-4-scout,zero,gpqa,0.795,0.796,0.222,0.182,0.783,0.808,0.51,...,0.0,0.0,0.25,0.0,0.05,97.701,76.095,7077.75,1313.333,0.49
21,llama-4-scout,baseline,simpleqa,0.583,0.600,0.600,0.200,0.667,0.500,0.40,...,0.0,0.0,0.18,0.0,0.25,17.784,9.372,1418.57,429.215,0.60
22,llama-4-scout,few,simpleqa,0.494,0.574,0.812,0.083,0.695,0.293,0.32,...,0.0,0.0,0.09,0.0,0.07,55.762,47.242,6324.04,491.583,0.68
23,llama-4-scout,zero,simpleqa,0.748,0.774,0.364,0.150,0.829,0.667,0.69,...,0.0,0.0,0.10,0.0,0.01,38.955,10.228,4093.40,415.481,0.31
24,nf-gpt-4o,baseline,gpqa,0.556,0.557,0.447,0.438,0.537,0.575,0.30,...,0.0,0.0,0.35,0.0,0.17,5.344,9.002,1140.58,548.662,0.70
25,nf-gpt-4o,few,gpqa,0.670,0.700,0.167,0.500,0.571,0.769,0.50,...,0.0,0.0,0.35,0.0,0.02,30.900,8.627,8593.42,1344.822,0.50
26,nf-gpt-4o,zero,gpqa,0.621,0.660,0.179,0.579,0.500,0.742,0.53,...,0.0,0.0,0.34,0.0,0.03,33.863,8.533,6043.14,1206.896,0.47
27,nf-gpt-4o,baseline,simpleqa,0.638,0.648,0.528,0.171,0.699,0.576,0.29,...,0.0,0.0,0.23,0.0,0.20,4.682,9.068,482.58,68.571,0.71
28,nf-gpt-4o,few,simpleqa,0.782,0.787,0.083,0.348,0.750,0.815,0.53,...,0.0,0.0,0.30,0.0,0.02,16.436,2.249,6100.83,316.415,0.47
29,nf-gpt-4o,zero,simpleqa,0.772,0.800,0.000,0.471,0.692,0.852,0.60,...,0.0,0.0,0.31,0.0,0.00,20.890,3.066,3765.60,313.735,0.40
30,nf-gpt-4o-mini,baseline,gpqa,0.456,0.522,0.268,0.786,0.267,0.645,0.31,...,0.0,0.0,0.52,0.0,0.14,15.665,12.253,3006.93,1824.420,0.69
31,nf-gpt-4o-mini,few,gpqa,0.361,0.566,0.091,1.000,0.000,0.723,0.47,...,0.0,0.0,0.50,0.0,0.00,29.396,7.157,8821.26,1138.869,0.53
32,nf-gpt-4o-mini,zero,gpqa,0.368,0.581,0.038,1.000,0.000,0.735,0.57,...,0.0,0.0,0.42,0.0,0.00,27.815,5.365,5816.23,909.068,0.43
33,nf-gpt-4o-mini,baseline,simpleqa,0.547,0.562,0.270,0.611,0.467,0.628,0.27,...,0.0,0.0,0.49,0.0,0.15,2.512,1.083,492.69,80.665,0.73
34,nf-gpt-4o-mini,few,simpleqa,0.517,0.520,0.621,0.286,0.556,0.478,0.50,...,0.0,0.0,0.17,0.0,0.07,15.596,1.829,6339.67,264.302,0.50
35,nf-gpt-4o-mini,zero,simpleqa,0.458,0.538,0.182,0.824,0.250,0.667,0.61,...,0.0,0.0,0.32,0.0,0.00,18.832,2.335,3820.86,261.960,0.39

In [226]:
latex = df2.to_latex(
    index=False,          # Set to False to hide index
    float_format=lambda x: f'{x:0.3g}',
    column_format=None,  # e.g., 'lrc' for left, right, center alignment
    longtable=False,     # Set to True for tables that span multiple pages
    caption="Evaluation of different judge models and evaluation prompts on three datasets (N=100).",        # Add a caption to your table
    label="tab:expresults",          # Add a label for cross-referencing
    position='htbp'        # e.g., 'h', 't', 'b', 'p' for table positioning
)
print(latex)

\begin{table}[htbp]
\caption{Evaluation of different judge models and evaluation prompts on three datasets (N=100).}
\label{tab:expresults}
\begin{tabular}{lllrrrrrr}
\toprule
Judge Model & Prompt & Dataset & Macro-F1 & Acc. & FPR & FNR & F1 (+) & F1 (-) \\
\midrule
claude-3-5-haiku-20241022 & baseline & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-haiku-20241022 & few & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-haiku-20241022 & zero & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-haiku-20241022 & baseline & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-haiku-20241022 & few & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-haiku-20241022 & zero & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-sonnet-20241022 & baseline & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-sonnet-20241022 & few & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-sonnet-20241022 & zero & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-sonnet-20241022 & baseline & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-sonnet-20241022 & few & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
claude-3-5-sonnet-20241022 & zero & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-maverick & baseline & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-maverick & few & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-maverick & zero & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-maverick & baseline & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-maverick & few & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-maverick & zero & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-scout & baseline & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-scout & few & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-scout & zero & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-scout & baseline & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-scout & few & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
llama-4-scout & zero & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o & baseline & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o & few & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o & zero & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o & baseline & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o & few & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o & zero & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o-mini & baseline & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o-mini & few & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o-mini & zero & gpqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o-mini & baseline & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o-mini & few & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
nf-gpt-4o-mini & zero & simpleqa & 0.772 & 0.8 & 0 & 0.471 & 0.692 & 0.852 \\
\bottomrule
\end{tabular}
\end{table}